run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - bodyclose
    - noctx
    - unconvert
    - unparam
    - gocritic

  disable:
    - typecheck

linters-settings:
  errcheck:
    check-blank: true
    exclude-functions:
      - (io.Closer).Close

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  goimports:
    local-prefixes: github.com/seslattery/hullcloak

  gosec:
    excludes:
      - G404

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false
      - name: unexported-return
        disabled: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - whyNoLint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    - text: "G101: Potential hardcoded credentials"
      linters:
        - gosec

  exclude-use-default: false
